"""Add prompt_version and agent_type to ChatHistory

Revision ID: 9041c08d06df
Revises: afc2ec187719
Create Date: 2025-06-02 14:05:57.082304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9041c08d06df'
down_revision: Union[str, None] = 'afc2ec187719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('prompt_version', sa.String(), nullable=True))
    op.add_column('chat_history', sa.Column('agent_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'agent_type')
    op.drop_column('chat_history', 'prompt_version')
    # ### end Alembic commands ###
